accounts/urls.py
from django.urls import path

from .views import SignUpView

name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

honeycomics/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pricing.urls"), name="pricing"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
]

pricing/urls.py
# pricing/urls.py

from django.urls import path

from .views import CreateCBSubscriptionView, PlanDetailView, PlanView, SubscriptionView, WebhookView

app_name = "pricing"

urlpatterns = [
    path("plans", PlanView.as_view(), name="plans"),
    path("plan/<str:pk>/", PlanDetailView.as_view(), name="plan-detail"),
    path("api/generate_checkout_new_url", CreateCBSubscriptionView.as_view()),
    path("webhooks", WebhookView.as_view()),
    path("subscription", SubscriptionView.as_view(), name="subscription"),
]

accounts/models.py
from django.db import models

# Create your models here.

pricing/models.py
from django.conf import settings
from django.db import models

from lib.chargebee.item import Item
from lib.chargebee.item_price import ItemPrice

# Create your models here.
# pricing/models.py


User = settings.AUTH_USER_MODEL


class Plan(models.Model):
    id = models.CharField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return self.name


def initialise_plan_list_from_chargebee():
    for item in Item.get_items():
        plan = Plan(id=item.id, name=item.name, description=item.description)
        plan.save()


class PlanPrice(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    price = models.IntegerField()
    currency = models.CharField(max_length=255, default="USD")
    period = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.period} {self.plan.name} {self.currency} plan"


def initialise_plan_price_list_from_chargebee():
    for item_price in ItemPrice.get_item_prices():
        print(item_price.id)
        print(item_price.item_id)
        print(item_price.price)
        print(item_price.currency_code)
        print(item_price.period_unit)
        plan = Plan.objects.get(id=item_price.item_id)
        plan_price = PlanPrice(
            id=item_price.id,
            plan=plan,
            price=item_price.price,
            currency=item_price.currency_code,
            period=item_price.period_unit,
        )
        plan_price.save()


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plan_price = models.ForeignKey(PlanPrice, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.user.username} {self.plan_price.plan.name}"

accounts/forms.py
# accounts/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text="Required. 30 characters or fewer.")
    last_name = forms.CharField(max_length=30, required=True, help_text="Required. 30 characters or fewer.")
    email = forms.EmailField(required=True, help_text="Required. Enter a valid email address.")

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "email")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import UserForm


class SignUpView(CreateView):
    form_class = UserForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

pricing/views.py
# pricing/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden, JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, View

from lib.chargebee.config import setted_chargebee

from .models import Plan, PlanPrice, Subscription


class PlanView(LoginRequiredMixin, ListView):
    model = Plan
    context_object_name = "plans"
    template_name = "pricing/plans.html"


class PlanDetailView(LoginRequiredMixin, DetailView):
    model = Plan
    context_object_name = "plan"
    template_name = "pricing/plan_detail.html"

    def get_context_data(self, **kwargs):
        context = super(PlanDetailView, self).get_context_data()
        context["plan_prices"] = PlanPrice.objects.filter(plan=self.get_object())
        return context


class CreateCBSubscriptionView(View):
    def post(self, request, *args, **kwargs):
        try:
            price_id = request.POST.get("price_id")

            # Use the received price_id in the checkout request
            result = setted_chargebee.HostedPage.checkout_new_for_items(
                {
                    "subscription_items": [
                        {"item_price_id": price_id},
                    ],
                    "customer": {
                        "first_name": request.user.first_name,
                        "last_name": request.user.last_name,
                        "email": request.user.email,
                    },
                }
            )

            # Extract hosted_page from the result
            hosted_page = result._response["hosted_page"]
            # Return the hosted_page data as JSON response
            return JsonResponse(hosted_page)
        except json.JSONDecodeError:
            return JsonResponse({"error": "Invalid JSON data in the request."}, status=400)


# EU region IP addresses
ALLOWED_IPS = [
    "127.0.0.1",
    "18.159.27.9",
    "18.159.5.237",
    "3.126.22.116",
    "3.124.98.200",
    "18.158.188.144",
    "18.197.55.93",
    "18.158.1.51",
    "18.159.186.201",
    "18.159.83.75",
    "3.121.1.124",
    "52.28.49.9",
    "52.58.215.160",
]


@method_decorator(csrf_exempt, name="dispatch")
class WebhookView(View):
    def post(self, request, *args, **kwargs):
        try:
            remote_ip = request.META.get("REMOTE_ADDR", None)
            if remote_ip in ALLOWED_IPS:
                event = json.loads(request.body)
                if event["event_type"] == "subscription_created":
                    content = event["content"]
                    email = content["customer"]["email"]
                    user = User.objects.get(email=email)
                    item_price_id = content["subscription"]["subscription_items"][0]["item_price_id"]
                    item_price = PlanPrice.objects.get(id=item_price_id)
                    Subscription.objects.create(user=user, plan_price=item_price)
                    return JsonResponse({"status": "success"}, status=200)
                else:
                    print("Unhandled event type")
                    return JsonResponse({"status": "success"}, status=200)
            else:
                return HttpResponseForbidden("Access denied: Request from unauthorized IP.")
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)


class SubscriptionView(LoginRequiredMixin, ListView):
    model = Subscription
    template_name = "pricing/subscription.html"
    context_object_name = "subscription"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subscription"] = Subscription.objects.filter(user=self.request.user).order_by("-created_at").first()
        return context

templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    {% load static %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"/>
    <title>{% block title %} {% endblock %}</title>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <!-- chargebee -->
    <script src="https://js.chargebee.com/v2/chargebee.js"></script>
    <!-- internal -->
    <script src="{% static 'pricing/checkout.js' %}"></script>
  </head>
<body>
  <div class="container my-5">
    <div class="d-flex justify-content-between flex-row">
      <h1>
        <a style="text-decoration:none; " class="text-dark" href="{% url 'pricing:plans' %}">Honey Comics</a>
      </h1>
      <div>
        {% if user.is_authenticated %}
        <div class="d-flex column-gap-4 flex-row">
          <h4>Hi {{ user.username }}</h4>
          <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button class="btn btn-dark" type="submit">logout</button>
          </form>
        </div>
        {% else %}
        <a class="btn btn-dark" href="{% url 'login' %}">Log In</a>
        <a class="btn btn-dark" href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
      </div>
    </div>
    {% block content %}{% endblock %}
  </div>
</body>
</html>

templates/pricing/plan_detail.html
{% extends "base.html" %} {% block title %} Buy Plan {% endblock title%} {% block content %}
<div class="card-deck my-5 p-3">
  <h5>{{plan.name}}</h5>
  <p>{{plan.description}}</p>
  {% csrf_token %}
  {% for price in plan_prices %}
  <div class="card my-3">
    <div class="card-body">
      <h5>{{price.period}} : {{price.currency}} {{ price.price }}</h5>
      <button class="checkout-button btn btn-primary" data-price="{{ price.id }}">
        Checkout
      </button>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

templates/pricing/plans.html
<!-- pricing/templates/pricing/plans.html -->

{% extends "base.html" %} {% block title %} Plans {% endblock title%} {% block content %}
<div class="row my-5">
  {% for plan in plans %}
  <div class="col card m-3 p-3">
    <div>
      <h5>{{plan.name}}</h5>
      <p>{{plan.description}}</p>
      <a href="{% url 'pricing:plan-detail' plan.id %}" class="btn btn-primary">View Detail</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

templates/pricing/subscription.html
{% extends "base.html" %} {% block title %} Success {% endblock title%} {% block content %}
<div class="alert alert-success my-5" role="alert">
  {% if subscription %} Thanks for subscribing! You are subscribed to
  <strong>{{ subscription.subscribed_to }}</strong> {% else %} Please subscribe to any
  <a href="{% url 'pricing:plans' %}"> plans</a>
  {% endif %}
</div>
{% endblock content %}